### ISSUE TITLE
Add compatibility with FMI/FMU standards to modelica_bridge

### ISSUE THREAD

**Issue by SSModelGit** [ModROS/modelica_bridge#4]
Current thoughts are to assume the FMU has been prepped by JModelica, and then use Python scripts to directly interface with the model.

**Comment by chrbertsch** [comment]
Couldn't this be realized via http://wiki.ros.org/fmi_adapter ?

**Comment by SSModelGit** [comment]
Thanks for pointing this out! That library seems very interesting - since I had completed an iteration of modelica_bridge before that started, I had missed this - I intend to take a better look at fmi_adapter and see if I can potentially integrate with/contribute to the library.

**Comment by ralph-lange** [comment]
Hi, I'm a colleague of Christian and authored the fmi_adapter package (https://github.com/boschresearch/fmi_adapter). This package basically provides a thin ROS adapter for the FMILibrary (https://jmodelica.org/FMILibrary/). Contributions from your side are very welcome! Best regards, Ralph
